import type { Config } from 'tailwindcss';
import tailwindcssAnimate from 'tailwindcss-animate';

export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './.storybook/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--color-background) / <alpha-value>)',
        foreground: 'hsl(var(--color-foreground) / <alpha-value>)',
        surface: 'hsl(var(--color-surface))',
        overlay: 'hsl(var(--color-overlay))',
        panel: 'hsl(var(--color-panel) / <alpha-value>)',
        focus: 'hsl(var(--color-focus) / <alpha-value>)',
        selection: 'hsl(var(--color-selection))',
        'default-9-contrast': 'hsl(var(--color-default-9-contrast) / <alpha-value>)',
        'primary-9-contrast': 'hsl(var(--color-primary-9-contrast) / <alpha-value>)',
        'danger-9-contrast': 'hsl(var(--color-danger-9-contrast) / <alpha-value>)',
        default: {
          1: 'hsl(var(--color-default-1) / <alpha-value>)',
          2: 'hsl(var(--color-default-2) / <alpha-value>)',
          3: 'hsl(var(--color-default-3) / <alpha-value>)',
          4: 'hsl(var(--color-default-4) / <alpha-value>)',
          5: 'hsl(var(--color-default-5) / <alpha-value>)',
          6: 'hsl(var(--color-default-6) / <alpha-value>)',
          7: 'hsl(var(--color-default-7) / <alpha-value>)',
          8: 'hsl(var(--color-default-8) / <alpha-value>)',
          9: 'hsl(var(--color-default-9) / <alpha-value>)',
          10: 'hsl(var(--color-default-10) / <alpha-value>)',
          11: 'hsl(var(--color-default-11) / <alpha-value>)',
          12: 'hsl(var(--color-default-12) / <alpha-value>)',
        },
        primary: {
          1: 'hsl(var(--color-primary-1) / <alpha-value>)',
          2: 'hsl(var(--color-primary-2) / <alpha-value>)',
          3: 'hsl(var(--color-primary-3) / <alpha-value>)',
          4: 'hsl(var(--color-primary-4) / <alpha-value>)',
          5: 'hsl(var(--color-primary-5) / <alpha-value>)',
          6: 'hsl(var(--color-primary-6) / <alpha-value>)',
          7: 'hsl(var(--color-primary-7) / <alpha-value>)',
          8: 'hsl(var(--color-primary-8) / <alpha-value>)',
          9: 'hsl(var(--color-primary-9) / <alpha-value>)',
          10: 'hsl(var(--color-primary-10) / <alpha-value>)',
          11: 'hsl(var(--color-primary-11) / <alpha-value>)',
          12: 'hsl(var(--color-primary-12) / <alpha-value>)',
        },
        danger: {
          1: 'hsl(var(--color-danger-1) / <alpha-value>)',
          2: 'hsl(var(--color-danger-2) / <alpha-value>)',
          3: 'hsl(var(--color-danger-3) / <alpha-value>)',
          4: 'hsl(var(--color-danger-4) / <alpha-value>)',
          5: 'hsl(var(--color-danger-5) / <alpha-value>)',
          6: 'hsl(var(--color-danger-6) / <alpha-value>)',
          7: 'hsl(var(--color-danger-7) / <alpha-value>)',
          8: 'hsl(var(--color-danger-8) / <alpha-value>)',
          9: 'hsl(var(--color-danger-9) / <alpha-value>)',
          10: 'hsl(var(--color-danger-10) / <alpha-value>)',
          11: 'hsl(var(--color-danger-11) / <alpha-value>)',
          12: 'hsl(var(--color-danger-12) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
